version: "3.5"

services:
  flask_app:
    container_name: flask_app
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: python manage.py run -h 0.0.0.0
    env_file:
      - ./.env.dev


  db:
    image: postgres:alpine3.17
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_upload_db

volumes:
  postgres_data:
